{
  id: $id,
  name: $name,
  temperature: 1.0,
  topP: 1.0,
  frequencyPenalty: 0,
  presencePenalty: 0,
  maxTokens: 4096,
  stopSequences: [],
  reasoningMode: "deepseek",
  post_prompt_processing: "none",
  impersonation_prompt: .impersonation_prompt,
  new_chat_prompt: .new_chat_prompt,
  new_group_chat_prompt: .new_group_chat_prompt,
  new_example_chat_prompt: .new_example_chat_prompt,
  continue_nudge_prompt: .continue_nudge_prompt,
  group_nudge_prompt: .group_nudge_prompt,
  scenario_format: .scenario_format,
  personality_format: .personality_format,
  wi_format: .wi_format,
  prompts: (.prompts + $extra_prompts),
  prompt_order: (.prompt_order[0].order // []) + $extra_order,
  isDefault: false,
  createdAt: (now * 1000 | floor),
  updatedAt: (now * 1000 | floor)
}
